### ISSUE TITLE
Pls public the source of Cycles for Max plugin

### ISSUE THREAD

**Issue by nguyenbs** [jlwitthuhn/cyclesformax-cycles#1]
Pls public the source of Cycles for Max plugin.
My team is willing to contribute

**Comment by jlwitthuhn** [comment]
Hello, apologies for the delay with releasing the source code. It is still coming and today I just released the next piece which is the code for configuring and building all the dependencies needed for the plugin available [here](https://github.com/jlwitthuhn/cyclesformax-dependencies).

The full source for the plugin itself will be coming by the end of August, I just want to clean it up a bit first. If I don't find time by then I just release it all as-is.

Will keep this issue open until full release is complete.

**Comment by jlwitthuhn** [comment]
Closing this out now as I just posted the code here https://github.com/jlwitthuhn/cyclesformax-opensource

The documentation is a little thin and I hope to improve it but that isn't worth holding up the release anymore. If you have any trouble getting it to build and run file an issue and I'll try to help.
